steps:
  - id: 'Populate Maven cache from bucket'
    name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - 'gs://hmf-build-caches/oncoact/.m2'
      - '/cache/.m2'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'

  - id: 'Build the jars'
    name: 'maven:3.9.1-eclipse-temurin-11'
    entrypoint: mvn
    args: [ 'package', '--batch-mode' ]
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2

  - id: 'Refresh bucket from local Maven cache after build'
    name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '/cache/.m2'
      - 'gs://hmf-build-caches/oncoact/.m2/'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'

  - id: 'Build image with public resources'
    name: 'eu.gcr.io/hmf-build/docker-tag'
    args: [ 'eu.gcr.io/hmf-build/oncoact', '$TAG_NAME', 'DockerfilePublic']

  - id: 'Build image with private resources'
    name: 'eu.gcr.io/hmf-build/docker-tag'
    args: [ 'eu.gcr.io/hmf-pipeline-prod-e45b00f2/oncoact', '$TAG_NAME', 'DockerfilePrivate' ]

logsBucket: 'gs://hmf-build-logs'
timeout: 4800s
options:
  machineType: 'E2_HIGHCPU_8'