steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Populating Maven cache from bucket'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - 'gs://hmf-build-caches/oncoact/.m2'
      - '/cache/.m2'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'

  - name: 'maven:3-jdk-11'
    id: 'Building the jars'
    entrypoint: mvn
    args: [ 'install' ]
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2

  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Refreshing bucket from local Maven cache after build'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '/cache/.m2'
      - 'gs://hmf-build-caches/oncoact/.m2/'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Building image with public resources'
    dir: '${_CHILD_PROJECT}'
    entrypoint: 'bash'
    args: [ '../docker-tag.sh', 'eu.gcr.io/hmf-build/${_CHILD_PROJECT}', '$TAG_NAME', 'DockerfilePublic', '${_CHILD_PROJECT}-' ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Pushing public image'
    args: [ 'push', 'eu.gcr.io/hmf-build/${_CHILD_PROJECT}', '--all-tags' ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Building image with private resources'
    dir: '${_CHILD_PROJECT}'
    entrypoint: 'bash'
    args: [ '../docker-tag.sh', 'eu.gcr.io/hmf-pipeline-prod-e45b00f2/${_CHILD_PROJECT}', '$TAG_NAME', 'DockerfilePrivate', '${_CHILD_PROJECT}-' ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Pushing private image'
    args: [ 'push', 'eu.gcr.io/hmf-pipeline-prod-e45b00f2/${_CHILD_PROJECT}', '--all-tags' ]

logsBucket: 'gs://hmf-build-logs'
timeout: 4800s
options:
  machineType: 'E2_HIGHCPU_8'