steps:
  - id: 'Build the jars using maven-cache'
    name: 'eu.gcr.io/hmf-build/maven-cache/alpine-java11'
    args: [ 'package --batch-mode' ]

  - id: 'Build image with public resources'
    name: 'eu.gcr.io/hmf-build/docker-tag'
    args: [ 'eu.gcr.io/hmf-build/oncoact', '$TAG_NAME', 'DockerfilePublic' ]

  - id: 'Build image with private resources'
    name: 'eu.gcr.io/hmf-build/docker-tag'
    args: [ 'eu.gcr.io/hmf-pipeline-prod-e45b00f2/oncoact', '$TAG_NAME', 'DockerfilePrivate' ]

logsBucket: 'gs://hmf-build-logs'
timeout: 4800s
options:
  machineType: 'E2_HIGHCPU_8'