DROP TABLE IF EXISTS `protect`;
CREATE TABLE `protect`
(   `id` int NOT NULL AUTO_INCREMENT,
    `modified` DATETIME NOT NULL,
    `sampleId` varchar(255) NOT NULL,
    `gene` varchar(255),
    `transcript` varchar(255),
    `isCanonical` BOOLEAN,
    `event` varchar(255) NOT NULL,
    `eventIsHighDriver` BOOLEAN,
    `germline` BOOLEAN NOT NULL,
    `reported` BOOLEAN NOT NULL,
    `studyNctId` varchar(50),
    `studyTitle` varchar(500),
    `studyAcronym` varchar(250),
    `studyGender` varchar(50),
    `countriesOfStudy` varchar(500),
    `treatment` varchar(255) NOT NULL,
    `treatmentApproachesDrugClass` varchar(500),
    `treatmentApproachesTherapy` varchar(500),
    `onLabel` BOOLEAN NOT NULL,
    `level` varchar(255) NOT NULL,
    `direction` varchar(255) NOT NULL,
    `source` varchar(255) NOT NULL,
    `sourceEvent` varchar(255) NOT NULL,
    `sourceUrls` varchar(2500),
    `evidenceType` varchar(50) NOT NULL,
    `rangeRank` int,
    `evidenceUrls` varchar(2500),
    PRIMARY KEY (`id`)
);
CREATE INDEX `protect_sampleId` ON `protect` (`sampleId`);