package com.hartwig.oncoact.orange.virus;

public enum VirusQCStatus {
    NO_ABNORMALITIES,
    LOW_VIRAL_COVERAGE,
    EXCESSIVE_VIRAL_COVERAGE,
    ASSEMBLY_DOWNSAMPLED,
    CHILD_TAXID_REFERENCE,
    UNCLEAR_TAXID_ASSIGNMENT
}
